Project roles, channels, reactions
ohbm/hackathon2022 pull request #71
Opened 2022-06-13 15:30 UTC by AKSoo

@anibalsolon This bot needs to restart when there are new/changed projects and KEEP running to handle reaction roles.

You'll need to figure out a way to edit github actions to accomplish this and host the bot somewhere reliable.

2022-06-13 15:47 UTC, anibalsolon requested changes
Hey @AKSoo thank you for the code!

Could you please move the roles, category and role message creation to the ensure discord channels?
Some things here need to be decouples, as the projects.yml will be updated upon the issue events. We still need the ensure.py.

The bot here will be only run once, and the `on_ready` will be run only once. So all that is bound to the issue trigger on Github will not be run.

2022-06-14 04:35 UTC, anibalsolon commented
@AKSoo I've pushed some code, please take a look

I've kept @ everyone with permission in the channels while we dont merge this PR.

https://github.com/ohbm/hackathon2022/pull/71/files#diff-3adf1426e3c0c973232ce6292599de9d844326eb462f0314eb9a1a3ca5297405R99

2022-06-14 07:13 UTC, AKSoo commented
> The bot here will be only run once, and the `on_ready` will be run only once. So all that is bound to the issue trigger on Github will not be run.

I was thinking Github Actions could send a signal to the bot host to restart the bot, but this is probably better for bot uptime, as long as the refreshing projects every minute isn't too taxing for the host. However, if the bot keeps projects up to date by itself, I don't think the Github Action and `ensure_discord_channels.py` is necessary at all.

2022-06-14 20:17 UTC, anibalsolon approved these changes

2022-06-14 20:17 UTC, merged